### ISSUE TITLE
saplings for trees

### ISSUE THREAD

**Issue by tobyplowy** [D00Med/farlands#103]
theres no saplings for the trees if farlands

**Comment by tobyplowy** [comment]
@D00Med fixed?

**Comment by D00Med** [comment]
Yep :)

**Comment by tobyplowy** [comment]
@D00Med they don't seem to grow but that's probably because trees take really long to grow in Minetest aperenly it can take up to 40 minutes :/

So I will close if all trees grow

**Comment by tobyplowy** [comment]
@D00Med all saplings have grown so thats good

**Comment by D00Med** [comment]
@tobyplowy You can use the watering can to test them, you left-click on the node below a sapling with it to make the sapling grow

**Comment by tobyplowy** [comment]
@D00Med why didn't you tell me this before waiting an hour for them to grow (yes it took that long) XD
