### ISSUE TITLE
update minetest game content

### ISSUE THREAD

**Issue by tobyplowy** [D00Med/farlands#104]
@D00Med can you update the minetest game content like the new chest animations and new blocks

**Comment by tobyplowy** [comment]
@D00Med done?

**Comment by D00Med** [comment]
@tobyplowy No, not yet

**Comment by D00Med** [comment]
Mostly is though

**Comment by tobyplowy** [comment]
@D00Med I can take it over from here

**Comment by D00Med** [comment]
@tobyplowy Just be careful you don't overwrite changes I've made
