### ISSUE TITLE
Submit textures here

### ISSUE THREAD

**Issue by LoneWolfHT** [D00Med/farlands#107]
After a certain amount of textures are approved I'll send a pull request to save you guys the time.

**Comment by tobyplowy** [comment]
@LoneWolfHT please upload the .png file instead of a screenshot you can do that by minimising the Internet window and just dropping it in from your desktop 
(this works on Windows but I'm not sure about Mac or Linux I guess it's the same)

Also please don't upload a .jpeg or .jpg I hate that junk!

**Comment by tobyplowy** [comment]
@LoneWolfHT So were are the textures?

**Comment by LoneWolfHT** [comment]
@tobyplowy None yet.
I'll be submitting them over time.
Question: What type of feel are they supposed to have? Dark? Realistic? Both? Other?

**Comment by tobyplowy** [comment]
@LoneWolfHT
They should be Bright but not too saturated also make them feel a bit retro

**Comment by LoneWolfHT** [comment]
@tobyplowy Not sure what retro means xD (Just a faint idea)

**Comment by tobyplowy** [comment]
@LoneWolfHT just Google nes graphics
(It means the style of old games)

**Comment by tobyplowy** [comment]
@LoneWolfHT i will have to close soon

**Comment by LoneWolfHT** [comment]
Ok. Having problems with my computer recently. Had to re-download MT.

**Comment by tobyplowy** [comment]
@LoneWolfHT i will close this issue
