### ISSUE TITLE
Anvil has a weird hitbox

### ISSUE THREAD

**Issue by kingoscargames** [D00Med/farlands#120]
![image](https://user-images.githubusercontent.com/29333817/30781252-ef8606d8-a11b-11e7-9596-d3316a8cef67.png)

**Comment by tobyplowy** [comment]
@kingoscargames yes I know I'm very bad with these hitboxes :/
I will ask d00med if he can help

**Comment by tobyplowy** [comment]
@kingoscargames keep the issues coming :)

**Comment by DS-Minetest** [comment]
You can make selection and collision boxes like node boxes.

**Comment by tobyplowy** [comment]
@DS-Minetest Ok

**Comment by D00Med** [comment]
@tobyplowy @DS-Minetest I can fix this

**Comment by D00Med** [comment]
Ok, it's done
