### ISSUE TITLE
Crops are rotting to fast

### ISSUE THREAD

**Issue by MarkuBu** [D00Med/farlands#127]
I like the idea of rotting crops, but they rot too quickly. They grow to fast in general. If you cultivate something, you have to maintain your plants permanently. No time for digging or building while farming.

The plants should grow more slowly and remain in the "mature" state for a while before rotting.

**Comment by tobyplowy** [comment]
@D00Med ping

**Comment by tobyplowy** [comment]
@MarkuBu keep them coming :)

**Comment by MarkuBu** [comment]
I close this issue because it is covered by #140
