### ISSUE TITLE
Yellow dandelion has wrong hitbox

### ISSUE THREAD

**Issue by MarkuBu** [D00Med/farlands#134]
The yellow dandelion hat the same hitbox as the rose, but should have the hitbox as the white dandelion

![screenshot_20171009_195722](https://user-images.githubusercontent.com/16163058/31382795-19d7fbc2-adb9-11e7-9aca-fbb5686d7c3d.png)

**Comment by MarkuBu** [comment]
It seems that the hitbox from MTG is still in use, but the texture has changed.

**Comment by MarkuBu** [comment]
Some other flowers also have a wrong hitbox

**Comment by D00Med** [comment]
see #184
