### ISSUE TITLE
Drop through beds when sleeping

### ISSUE THREAD

**Issue by MarkuBu** [D00Med/farlands#138]
I always drop through a bed if I'm sleeping. Seems to be an issue with the beds mod. Doesn't happen with MTG

![screenshot_20171010_134410](https://user-images.githubusercontent.com/16163058/31384873-26481902-adc1-11e7-8827-50485aad4eb8.png)

**Comment by MarkuBu** [comment]
Fixed this (hopefully). Please test. If it works for you too I merge it to 1.1 and master. Check this branch

https://github.com/D00Med/farlands/tree/beddrop

**Comment by tobyplowy** [comment]
@MarkuBu how do I test this?
Do I fork your branch?

**Comment by tobyplowy** [comment]
@MarkuBu ok I think I found it

**Comment by tobyplowy** [comment]
@MarkuBu Yeh I can walk around when I'm in the bed XD

**Comment by tobyplowy** [comment]
@MarkuBu now that you're at it can you add a fading effect to black so it looks like your closeing your eyes when you sleep?

**Comment by MarkuBu** [comment]
For all others to test this (if you use git)

go to your farlands folder
type: 
git pull
git checkout beddrop

Then start the game. To get back to whatever branch type e.g.
git checkout 1.1

I don't know if something like a fading effect is possible.

**Comment by tobyplowy** [comment]
@MarkuBu Apart from the fact that I can walk around while I'm in the bed 
I didn't find any other problems

**Comment by MarkuBu** [comment]
Yeah, will check this too

**Comment by MarkuBu** [comment]
No, I can't move now.

**Comment by MarkuBu** [comment]
Pushed the bugfix to 1.1

**Comment by tobyplowy** [comment]
@MarkuBu close?
