### ISSUE TITLE
Add Minetest and Minetest subgame to the repository topic or description for discoverability

### ISSUE THREAD

**Issue by 22i** [D00Med/farlands#150]
![screenshot_20171021_120208](https://user-images.githubusercontent.com/17874916/31850729-b0ad94fc-b657-11e7-85e4-9da8cbf11dbb.png)
you can add topics next to the repository description

for much more Farlands hits discoverability and visibilty when searching github for recently updated minetest things

this will make Farlands show up when you search for minetest on github.

github mintest search https://github.com/search?o=desc&q=minetest&s=updated&type=Repositories&utf8=%E2%9C%93

**Comment by tobyplowy** [comment]
@D00Med have a look at this

**Comment by D00Med** [comment]
@22i Ok, thanks for pointing this out. I've added "minetest" and "minetest-subgame"

**Comment by tobyplowy** [comment]
@D00Med close?

**Comment by D00Med** [comment]
@tobyplowy Oh yes, thanks
