### ISSUE TITLE
working version

### ISSUE THREAD

**Issue by farfadet46** [D00Med/farlands#78]
Hello nice work on this subgame :)

so, can you tell me how to play ? like the savanah stone, there is a craft with it ? no slab, no furnace... maybe i'm lost in temporal error XD

so continue the good work !

**Comment by tobyplowy** [comment]
@farfadet46 It's Still very work in progress so jeh

Also thanks

**Comment by D00Med** [comment]
I _just_ started typing xD

**Comment by tobyplowy** [comment]
@D00Med XD

**Comment by farfadet46** [comment]
XD thanks ;)

**Comment by tobyplowy** [comment]
@D00Med can this be closed?

**Comment by farfadet46** [comment]
yep thanks :)

**Comment by tobyplowy** [comment]
@farfadet46 perhaps would you be interested in helping the project?
We need sounds textures and programers (and probably later bug testers)
we also need suggestions and ideas

If you are interested please let me know :)

**Comment by farfadet46** [comment]
yep, if you need tester i'm here ;)
Actualy i made some models under blender for 3D printing and of course Minetest. but i'm realy bad at texturing

**Comment by D00Med** [comment]
That's great :)

**Comment by tobyplowy** [comment]
> yep, if you need tester i'm here ;)

That's amazing :)
