### ISSUE TITLE
problem with sea_grass

### ISSUE THREAD

**Issue by farfadet46** [D00Med/farlands#79]
wen dig sea_grass return an unknown item
![screenshot_20170327_152338](https://cloud.githubusercontent.com/assets/11613522/24358547/c5a4a728-1301-11e7-90cc-f7054f18471d.png)

i found it here ?
https://github.com/D00Med/farlands/blob/76e2893290cd666746ae8e82c6fa93698899d041/mods/mapgen/nodes.lua#L1570
maybe the drop can be cobblestone ?

**Comment by D00Med** [comment]
aah right, someone put in an extra colon.
It will be fixed in my next commit

**Comment by tobyplowy** [comment]
> someone put in an extra colon.

Vote for Toby plowy 2017 as president
"I have no idea what I'm doing XD"

**Comment by tobyplowy** [comment]
@D00Med is this fixed?

**Comment by D00Med** [comment]
I think so yes
