### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by tacotexmex** [D00Med/farlands#80]
I experience random crashes not only of the game but the whole Minetest client as well. This has only happened in Farlands. Is it due to Farlands being developed towards 0.4.16, or perhaps a memory issue?

I'm on a MacBook Pro with 8 GB RAM and Intel HD Graphics 3000 512 MB. 

The only error message I get before crash is
> [1]    15424 segmentation fault  /Applications/minetest.app/Contents/MacOS/minetest

**Comment by D00Med** [comment]
Are there no other related errors in the debug file?

**Comment by tacotexmex** [comment]
I ran it again and this time, right before the segfault, it says
``` 2017-04-18 19:09:55: WARNING[Emerge-0]: Assignment to undeclared global "n_switch" inside a function at ...tion Support/minetest/games/farlands/mods/mines/init.lua:104.
2017-04-18 19:09:55: WARNING[Emerge-0]: Assignment to undeclared global "x5" inside a function at ...tion Support/minetest/games/farlands/mods/mines/init.lua:130.
2017-04-18 19:09:55: WARNING[Emerge-0]: Assignment to undeclared global "z5" inside a function at ...tion Support/minetest/games/farlands/mods/mines/init.lua:136.
2017-04-18 19:09:55: ACTION[Emerge-0]: Created mine at (76,-85,129)

**Comment by tacotexmex** [comment]
Ran it one more time and yes, it seems like it is the mines causing trouble:
```2017-04-18 19:12:41: WARNING[Emerge-0]: Assignment to undeclared global "n_switch" inside a function at ...tion Support/minetest/games/farlands/mods/mines/init.lua:104.
2017-04-18 19:12:41: WARNING[Emerge-0]: Assignment to undeclared global "x5" inside a function at ...tion Support/minetest/games/farlands/mods/mines/init.lua:166.
2017-04-18 19:12:41: WARNING[Emerge-0]: Assignment to undeclared global "z5" inside a function at ...tion Support/minetest/games/farlands/mods/mines/init.lua:172.
2017-04-18 19:12:41: ACTION[Emerge-0]: Created mine at (130,-112,116)

**Comment by DS-Minetest** [comment]
Let's see if it's still there with #81. But that won't be because global variables normally don't cause crashes.

**Comment by tacotexmex** [comment]
I'm not that versed in coding and debugging, should I add it after each line within the `if cnt == 0 then` statement?

**Comment by DS-Minetest** [comment]
@tacotexmex Just edit line 231-216 to something like
```
		minetest.log("action", "Created mine at ("..mpos.x..","..mpos.y..","..mpos.z..")")
		local out2 = make_mine(p2,p3,mpos,vm_data,vx_area,1)
		minetest.log("action", "bla1")
		local out3 = make_mine(p3,p2,mpos,out2,vx_area,2)
		minetest.log("action", "bla2")
		return out3
```

**Comment by tobyplowy** [comment]
Is this fixed already can this be closed?

**Comment by tacotexmex** [comment]
I need to check with 0.4.16 client

**Comment by DS-Minetest** [comment]
The issue pointed out in this issue is actually not a bug. `segmentation fault` (in german `Speicherzugriffsfehler`) is normal and not the fault of farlands.

**Comment by tobyplowy** [comment]
@DS-Minetest so it's invalid?

**Comment by tacotexmex** [comment]
I've only had segfault with Farlands, and I've tried a lot of subgames. Let's see if it resolves with .4.16.

**Comment by tobyplowy** [comment]
@tacotexmex and is it fixed with with .4.16.

**Comment by tacotexmex** [comment]
I still need to test, sorry for stalling.

**Comment by tobyplowy** [comment]
> stalling

no idea what that means but your forgiven XD

**Comment by tobyplowy** [comment]
@tacotexmex if you test can you report back

**Comment by tobyplowy** [comment]
@tacotexmex is this fixed for you by using the newest version of mt?

**Comment by tacotexmex** [comment]
Several mines has been created without crashing now that I test with a stable 0.4.16, so it should be safe to say that the bug is now fixed.
