### ISSUE TITLE
Player model on wrong place in boat.

### ISSUE THREAD

**Issue by DS-Minetest** [D00Med/farlands#83]
(It's the vehicle boat.)
![screenshot_20170419_230541](https://cloud.githubusercontent.com/assets/7613443/25202362/671a25be-2555-11e7-99f8-b3458ee99d8b.png)
(Also the selection box is on wrong place and has wrong size.)

**Comment by tobyplowy** [comment]
@DS-Minetest What do you mean this is a problem it's completely normal to put your head in the bottom of the boat and sit in the water lol jk

**Comment by D00Med** [comment]
What is wrong with the selection box? I thought it was good. 
I made it a bit bigger, and fixed the player. I did the same for the air balloon.

**Comment by tobyplowy** [comment]
Is this fixed already can this be closed?
